class date  //structure  object : state, behaviour ,identity,and responsibility.
{
	int day ,month, year;
	String dow;

	// default  constructor .  ... 
		
	date()			
	{	
		this.day=15;		
		this.month=02;
		this.year=2026;
		this.dow="Sunday";	
	}


	date(int d, int m ,int y,String  str)	// parameterized constructor :   note : passing parameters when creating object of an class initialized ..
						
	{						
		this.day=d;
		this.month=m;	
		this.year=y;
		this.dow=str;				 		 

    void setday(int d)
    {
        this.day = d;   					
    }

    void setmonth(int m)
    {
        this.month = m;
    }

    void setyear(int y)		
			
    {
        this.year = y;
    }

    void setdow(String str)
    {
        this.dow = str;
    }
	

    	int getday()			
    	{
        	return day;
    	}

    	int getmonth()
    	{
        		return month;
    	}

    	int getyear()
    	{
        		return year;
    	}

    	String getdow()
    	{
        		return dow;  
    	}

   void display()			// displayed the state of the object 
    {
     	System.out.println("Day   : " + day);
        	System.out.println("Month : " + month);
        	System.out.println("Year  : " + year);
        	System.out.println("DOW   : " + dow);
    }
		

}//class date ends here 
class Test
{		
					//main we also can called as an behaviour // function 
	public static void main(String args[] )  // *main*  method  called by the class loader in JVM 
	{
		date d1;			 //reference unique code generated  hashcode is generated by the  JVM // or refer has 
					// an pointer to access the heap memory 
					
		d1=new date();   	 // passed the parameter during the object creation as an defaul using the parameters .. 
					// this is genrated in the heap memory with new keyword  .object  
	
		//d1.setday();		//invoked with the value set here 
		//d1.setmonth();		 	
		//d1.setyear();		 	
		d1.setdow("Monday");	
		
		
		d1.display();  // display call for object d1
				
				
	}
}


	